// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMgPMO-cT2vF1rYmk0nwAHW3M-gnfPCE',
    appId: '1:897622405766:web:603bdaf5e12985b08c5707',
    messagingSenderId: '897622405766',
    projectId: 'fruit-hub-a22e8',
    authDomain: 'fruit-hub-a22e8.firebaseapp.com',
    storageBucket: 'fruit-hub-a22e8.firebasestorage.app',
    measurementId: 'G-GZRV7DSTGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSs6lkibq0ideDYSE0hVnBdduX7VnYXd8',
    appId: '1:897622405766:android:eff0840afc163e338c5707',
    messagingSenderId: '897622405766',
    projectId: 'fruit-hub-a22e8',
    storageBucket: 'fruit-hub-a22e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd5BRGFumWWr-7xVBmd7aDGi9iu9pvDNE',
    appId: '1:897622405766:ios:87dcb10dc973d3178c5707',
    messagingSenderId: '897622405766',
    projectId: 'fruit-hub-a22e8',
    storageBucket: 'fruit-hub-a22e8.firebasestorage.app',
    androidClientId: '897622405766-meu8m8lnp8kqccgsaoba9uopb0o26k5n.apps.googleusercontent.com',
    iosClientId: '897622405766-isop9cee437kee2q51teqarh3i126o6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.frutiHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd5BRGFumWWr-7xVBmd7aDGi9iu9pvDNE',
    appId: '1:897622405766:ios:87dcb10dc973d3178c5707',
    messagingSenderId: '897622405766',
    projectId: 'fruit-hub-a22e8',
    storageBucket: 'fruit-hub-a22e8.firebasestorage.app',
    androidClientId: '897622405766-meu8m8lnp8kqccgsaoba9uopb0o26k5n.apps.googleusercontent.com',
    iosClientId: '897622405766-isop9cee437kee2q51teqarh3i126o6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.frutiHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoMgPMO-cT2vF1rYmk0nwAHW3M-gnfPCE',
    appId: '1:897622405766:web:d8b94996617751f88c5707',
    messagingSenderId: '897622405766',
    projectId: 'fruit-hub-a22e8',
    authDomain: 'fruit-hub-a22e8.firebaseapp.com',
    storageBucket: 'fruit-hub-a22e8.firebasestorage.app',
    measurementId: 'G-W9E8QY4BKY',
  );
}
